- id: fencechecker
  name: fencechecker
  description: Check Python fenced code blocks in Markdown files.
  language: python
  language_version: '3.13'
  minimum_pre_commit_version: '4.2.0'
  entry: fencechecker
  types: [markdown]
